services:

  nginx:
    image: nginx
    container_name: hw19_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/var/www/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    working_dir: /var/www/
    depends_on:
      - php
    networks:
      - hw19-network

  php:
    image: php:8.0
    container_name: hw19_php
    build: ./docker/php
    volumes:
      - ./www/:/var/www/
      - ./docker/php/conf.d/browscap.ini:/usr/local/etc/php/conf.d/browscap.ini
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /var/www/
    networks:
      - hw19-network

  mysql:
    ports:
      - "3306:3306"
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "hw19"
    volumes:
      - dbOtus:/var/lib/mysql
    networks:
      - hw19-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hw19_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - hw19-network

networks:
  hw19-network:
    driver: bridge

volumes:
  dbOtus:
